
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_tcn_network.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_TCN_NETWORK_H
#define __STAI_ATON_TCN_NETWORK_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_TCN_NETWORK_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_TCN_NETWORK_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_tcn_network_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_tcn_network_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_tcn_network_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_tcn_network_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_tcn_network_get_context_size(void)
{
  return STAI_TCN_NETWORK_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_tcn_network_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_tcn_network_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_tcn_network_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_tcn_network_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_tcn_network_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_tcn_network_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_tcn_network_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_tcn_network_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_tcn_network_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_tcn_network_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_tcn_network_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_tcn_network_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_tcn_network_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_tcn_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_tcn_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_tcn_network_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_tcn_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_tcn_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_tcn_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_tcn_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_tcn_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_tcn_network_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_tcn_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_tcn_network_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_tcn_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_tcn_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_tcn_network_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_tcn_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_tcn_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_tcn_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_tcn_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_tcn_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_tcn_network_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_tcn_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_tcn_network_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_tcn_network_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_tcn_network_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_TCN_NETWORK_STATES_NUM  (0)
#define STAI_TCN_NETWORK_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_TCN_NETWORK_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_TCN_NETWORK_IN_NUM (1)
#define STAI_TCN_NETWORK_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_TCN_NETWORK_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_TCN_NETWORK_IN_FORMATS \
  { \
    STAI_FORMAT_FLOAT32 \
  }
#define STAI_TCN_NETWORK_IN_SIZES \
  { \
    3300 \
  }
#define STAI_TCN_NETWORK_IN_SIZES_BYTES \
  { \
    13200 \
  }

#define STAI_TCN_NETWORK_IN_1_ALIGNMENT (32)
#define STAI_TCN_NETWORK_IN_1_NAME "Input_0_out_0"
#define STAI_TCN_NETWORK_IN_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_FIRST)
#define STAI_TCN_NETWORK_IN_1_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_IN_1_SIZE (3300)
#define STAI_TCN_NETWORK_IN_1_SIZE_BYTES (13200)
#define STAI_TCN_NETWORK_IN_1_CHANNEL (1)
#define STAI_TCN_NETWORK_IN_1_HEIGHT (55)
#define STAI_TCN_NETWORK_IN_1_WIDTH (60)
#define STAI_TCN_NETWORK_IN_1_BATCH (1)
#define STAI_TCN_NETWORK_IN_1_RANK (3)
#define STAI_TCN_NETWORK_IN_1_SHAPE \
  { \
    55, 60, 1 \
  }
#define STAI_TCN_NETWORK_IN_1_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_IN_1_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_IN_1_OFFSETS \
  { \
  }

/********************************** OUTPUTS **********************************/
#define STAI_TCN_NETWORK_OUT_NUM (1)
#define STAI_TCN_NETWORK_OUT_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_TCN_NETWORK_OUT_NAMES \
  { \
    "Gather_56_out_0" \
  }
#define STAI_TCN_NETWORK_OUT_FORMATS \
  { \
    STAI_FORMAT_FLOAT32 \
  }
#define STAI_TCN_NETWORK_OUT_SIZES \
  { \
    2 \
  }
#define STAI_TCN_NETWORK_OUT_SIZES_BYTES \
  { \
    8 \
  }

#define STAI_TCN_NETWORK_OUT_1_ALIGNMENT (32)
#define STAI_TCN_NETWORK_OUT_1_NAME "Gather_56_out_0"
#define STAI_TCN_NETWORK_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_TCN_NETWORK_OUT_1_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_OUT_1_SIZE (2)
#define STAI_TCN_NETWORK_OUT_1_SIZE_BYTES (8)
#define STAI_TCN_NETWORK_OUT_1_CHANNEL (1)
#define STAI_TCN_NETWORK_OUT_1_HEIGHT (1)
#define STAI_TCN_NETWORK_OUT_1_WIDTH (2)
#define STAI_TCN_NETWORK_OUT_1_RANK (2)
#define STAI_TCN_NETWORK_OUT_1_SHAPE \
  { \
    1, 2 \
  }
#define STAI_TCN_NETWORK_OUT_1_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_OUT_1_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_OUT_1_OFFSETS \
  { \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_TCN_NETWORK_WEIGHTS_NUM (23)
#define STAI_TCN_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
    32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 16, 32, 32, 32, 16, 32 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_NAMES \
  { \
    "Conv2D_2_weights", "Conv2D_2_bias", "Conv2D_5_weights", "Conv2D_5_bias", "Conv2D_10_weights", "Conv2D_10_bias", "Conv2D_17_weights", "Conv2D_17_bias", "Conv2D_22_weights", "Conv2D_22_bias", "Conv2D_28_weights", "Conv2D_28_bias", "Conv2D_31_weights", "Conv2D_31_bias", "Conv2D_36_weights", "Conv2D_36_bias", "Conv2D_42_weights", "Conv2D_42_bias", "Conv2D_45_weights", "Conv2D_45_bias", "Conv2D_50_weights", "Conv2D_50_bias", "Gather_56_param1" \
  }
#define STAI_TCN_NETWORK_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_S32 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_SIZES \
  { \
    3520, 64, 10560, 64, 12288, 64, 12288, 64, 12288, 64, 8192, 128, 24576, 128, 49152, 128, 256, 2, 768, 2, 12, 2, 1 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
    14080, 256, 42240, 256, 49152, 256, 49152, 256, 49152, 256, 32768, 512, 98304, 512, 196608, 512, 1024, 8, 3072, 8, 48, 8, 4 \
  }

#define STAI_TCN_NETWORK_WEIGHTS_1_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_1_NAME "Conv2D_2_weights"
#define STAI_TCN_NETWORK_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_1_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_1_SIZE (3520)
#define STAI_TCN_NETWORK_WEIGHTS_1_SIZE_BYTES (14080)
#define STAI_TCN_NETWORK_WEIGHTS_1_CHANNEL (55)
#define STAI_TCN_NETWORK_WEIGHTS_1_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_1_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_1_BATCH (55)
#define STAI_TCN_NETWORK_WEIGHTS_1_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_1_SHAPE \
  { \
    64, 1, 1, 55 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_1_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_1_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_1_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_2_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_2_NAME "Conv2D_2_bias"
#define STAI_TCN_NETWORK_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_2_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_2_SIZE (64)
#define STAI_TCN_NETWORK_WEIGHTS_2_SIZE_BYTES (256)
#define STAI_TCN_NETWORK_WEIGHTS_2_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_2_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_2_WIDTH (64)
#define STAI_TCN_NETWORK_WEIGHTS_2_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_2_SHAPE \
  { \
    64 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_2_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_2_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_2_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_3_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_3_NAME "Conv2D_5_weights"
#define STAI_TCN_NETWORK_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_3_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_3_SIZE (10560)
#define STAI_TCN_NETWORK_WEIGHTS_3_SIZE_BYTES (42240)
#define STAI_TCN_NETWORK_WEIGHTS_3_CHANNEL (55)
#define STAI_TCN_NETWORK_WEIGHTS_3_HEIGHT (3)
#define STAI_TCN_NETWORK_WEIGHTS_3_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_3_BATCH (55)
#define STAI_TCN_NETWORK_WEIGHTS_3_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_3_SHAPE \
  { \
    64, 3, 1, 55 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_3_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_3_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_3_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_4_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_4_NAME "Conv2D_5_bias"
#define STAI_TCN_NETWORK_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_4_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_4_SIZE (64)
#define STAI_TCN_NETWORK_WEIGHTS_4_SIZE_BYTES (256)
#define STAI_TCN_NETWORK_WEIGHTS_4_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_4_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_4_WIDTH (64)
#define STAI_TCN_NETWORK_WEIGHTS_4_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_4_SHAPE \
  { \
    64 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_4_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_4_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_4_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_5_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_5_NAME "Conv2D_10_weights"
#define STAI_TCN_NETWORK_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_5_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_5_SIZE (12288)
#define STAI_TCN_NETWORK_WEIGHTS_5_SIZE_BYTES (49152)
#define STAI_TCN_NETWORK_WEIGHTS_5_CHANNEL (64)
#define STAI_TCN_NETWORK_WEIGHTS_5_HEIGHT (3)
#define STAI_TCN_NETWORK_WEIGHTS_5_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_5_BATCH (64)
#define STAI_TCN_NETWORK_WEIGHTS_5_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_5_SHAPE \
  { \
    64, 3, 1, 64 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_5_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_5_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_5_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_6_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_6_NAME "Conv2D_10_bias"
#define STAI_TCN_NETWORK_WEIGHTS_6_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_6_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_6_SIZE (64)
#define STAI_TCN_NETWORK_WEIGHTS_6_SIZE_BYTES (256)
#define STAI_TCN_NETWORK_WEIGHTS_6_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_6_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_6_WIDTH (64)
#define STAI_TCN_NETWORK_WEIGHTS_6_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_6_SHAPE \
  { \
    64 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_6_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_6_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_6_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_7_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_7_NAME "Conv2D_17_weights"
#define STAI_TCN_NETWORK_WEIGHTS_7_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_7_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_7_SIZE (12288)
#define STAI_TCN_NETWORK_WEIGHTS_7_SIZE_BYTES (49152)
#define STAI_TCN_NETWORK_WEIGHTS_7_CHANNEL (64)
#define STAI_TCN_NETWORK_WEIGHTS_7_HEIGHT (3)
#define STAI_TCN_NETWORK_WEIGHTS_7_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_7_BATCH (64)
#define STAI_TCN_NETWORK_WEIGHTS_7_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_7_SHAPE \
  { \
    64, 3, 1, 64 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_7_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_7_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_7_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_8_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_8_NAME "Conv2D_17_bias"
#define STAI_TCN_NETWORK_WEIGHTS_8_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_8_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_8_SIZE (64)
#define STAI_TCN_NETWORK_WEIGHTS_8_SIZE_BYTES (256)
#define STAI_TCN_NETWORK_WEIGHTS_8_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_8_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_8_WIDTH (64)
#define STAI_TCN_NETWORK_WEIGHTS_8_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_8_SHAPE \
  { \
    64 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_8_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_8_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_8_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_9_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_9_NAME "Conv2D_22_weights"
#define STAI_TCN_NETWORK_WEIGHTS_9_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_9_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_9_SIZE (12288)
#define STAI_TCN_NETWORK_WEIGHTS_9_SIZE_BYTES (49152)
#define STAI_TCN_NETWORK_WEIGHTS_9_CHANNEL (64)
#define STAI_TCN_NETWORK_WEIGHTS_9_HEIGHT (3)
#define STAI_TCN_NETWORK_WEIGHTS_9_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_9_BATCH (64)
#define STAI_TCN_NETWORK_WEIGHTS_9_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_9_SHAPE \
  { \
    64, 3, 1, 64 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_9_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_9_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_9_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_10_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_10_NAME "Conv2D_22_bias"
#define STAI_TCN_NETWORK_WEIGHTS_10_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_10_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_10_SIZE (64)
#define STAI_TCN_NETWORK_WEIGHTS_10_SIZE_BYTES (256)
#define STAI_TCN_NETWORK_WEIGHTS_10_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_10_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_10_WIDTH (64)
#define STAI_TCN_NETWORK_WEIGHTS_10_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_10_SHAPE \
  { \
    64 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_10_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_10_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_10_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_11_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_11_NAME "Conv2D_28_weights"
#define STAI_TCN_NETWORK_WEIGHTS_11_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_11_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_11_SIZE (8192)
#define STAI_TCN_NETWORK_WEIGHTS_11_SIZE_BYTES (32768)
#define STAI_TCN_NETWORK_WEIGHTS_11_CHANNEL (64)
#define STAI_TCN_NETWORK_WEIGHTS_11_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_11_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_11_BATCH (64)
#define STAI_TCN_NETWORK_WEIGHTS_11_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_11_SHAPE \
  { \
    128, 1, 1, 64 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_11_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_11_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_11_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_12_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_12_NAME "Conv2D_28_bias"
#define STAI_TCN_NETWORK_WEIGHTS_12_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_12_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_12_SIZE (128)
#define STAI_TCN_NETWORK_WEIGHTS_12_SIZE_BYTES (512)
#define STAI_TCN_NETWORK_WEIGHTS_12_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_12_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_12_WIDTH (128)
#define STAI_TCN_NETWORK_WEIGHTS_12_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_12_SHAPE \
  { \
    128 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_12_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_12_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_12_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_13_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_13_NAME "Conv2D_31_weights"
#define STAI_TCN_NETWORK_WEIGHTS_13_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_13_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_13_SIZE (24576)
#define STAI_TCN_NETWORK_WEIGHTS_13_SIZE_BYTES (98304)
#define STAI_TCN_NETWORK_WEIGHTS_13_CHANNEL (64)
#define STAI_TCN_NETWORK_WEIGHTS_13_HEIGHT (3)
#define STAI_TCN_NETWORK_WEIGHTS_13_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_13_BATCH (64)
#define STAI_TCN_NETWORK_WEIGHTS_13_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_13_SHAPE \
  { \
    128, 3, 1, 64 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_13_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_13_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_13_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_14_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_14_NAME "Conv2D_31_bias"
#define STAI_TCN_NETWORK_WEIGHTS_14_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_14_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_14_SIZE (128)
#define STAI_TCN_NETWORK_WEIGHTS_14_SIZE_BYTES (512)
#define STAI_TCN_NETWORK_WEIGHTS_14_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_14_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_14_WIDTH (128)
#define STAI_TCN_NETWORK_WEIGHTS_14_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_14_SHAPE \
  { \
    128 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_14_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_14_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_14_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_15_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_15_NAME "Conv2D_36_weights"
#define STAI_TCN_NETWORK_WEIGHTS_15_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_15_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_15_SIZE (49152)
#define STAI_TCN_NETWORK_WEIGHTS_15_SIZE_BYTES (196608)
#define STAI_TCN_NETWORK_WEIGHTS_15_CHANNEL (128)
#define STAI_TCN_NETWORK_WEIGHTS_15_HEIGHT (3)
#define STAI_TCN_NETWORK_WEIGHTS_15_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_15_BATCH (128)
#define STAI_TCN_NETWORK_WEIGHTS_15_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_15_SHAPE \
  { \
    128, 3, 1, 128 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_15_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_15_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_15_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_16_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_16_NAME "Conv2D_36_bias"
#define STAI_TCN_NETWORK_WEIGHTS_16_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_16_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_16_SIZE (128)
#define STAI_TCN_NETWORK_WEIGHTS_16_SIZE_BYTES (512)
#define STAI_TCN_NETWORK_WEIGHTS_16_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_16_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_16_WIDTH (128)
#define STAI_TCN_NETWORK_WEIGHTS_16_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_16_SHAPE \
  { \
    128 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_16_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_16_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_16_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_17_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_17_NAME "Conv2D_42_weights"
#define STAI_TCN_NETWORK_WEIGHTS_17_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_17_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_17_SIZE (256)
#define STAI_TCN_NETWORK_WEIGHTS_17_SIZE_BYTES (1024)
#define STAI_TCN_NETWORK_WEIGHTS_17_CHANNEL (128)
#define STAI_TCN_NETWORK_WEIGHTS_17_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_17_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_17_BATCH (128)
#define STAI_TCN_NETWORK_WEIGHTS_17_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_17_SHAPE \
  { \
    2, 1, 1, 128 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_17_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_17_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_17_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_18_ALIGNMENT (16)
#define STAI_TCN_NETWORK_WEIGHTS_18_NAME "Conv2D_42_bias"
#define STAI_TCN_NETWORK_WEIGHTS_18_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_18_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_18_SIZE (2)
#define STAI_TCN_NETWORK_WEIGHTS_18_SIZE_BYTES (8)
#define STAI_TCN_NETWORK_WEIGHTS_18_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_18_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_18_WIDTH (2)
#define STAI_TCN_NETWORK_WEIGHTS_18_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_18_SHAPE \
  { \
    2 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_18_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_18_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_18_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_19_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_19_NAME "Conv2D_45_weights"
#define STAI_TCN_NETWORK_WEIGHTS_19_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_19_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_19_SIZE (768)
#define STAI_TCN_NETWORK_WEIGHTS_19_SIZE_BYTES (3072)
#define STAI_TCN_NETWORK_WEIGHTS_19_CHANNEL (128)
#define STAI_TCN_NETWORK_WEIGHTS_19_HEIGHT (3)
#define STAI_TCN_NETWORK_WEIGHTS_19_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_19_BATCH (128)
#define STAI_TCN_NETWORK_WEIGHTS_19_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_19_SHAPE \
  { \
    2, 3, 1, 128 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_19_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_19_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_19_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_20_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_20_NAME "Conv2D_45_bias"
#define STAI_TCN_NETWORK_WEIGHTS_20_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_20_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_20_SIZE (2)
#define STAI_TCN_NETWORK_WEIGHTS_20_SIZE_BYTES (8)
#define STAI_TCN_NETWORK_WEIGHTS_20_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_20_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_20_WIDTH (2)
#define STAI_TCN_NETWORK_WEIGHTS_20_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_20_SHAPE \
  { \
    2 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_20_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_20_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_20_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_21_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_21_NAME "Conv2D_50_weights"
#define STAI_TCN_NETWORK_WEIGHTS_21_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_WEIGHTS_21_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_21_SIZE (12)
#define STAI_TCN_NETWORK_WEIGHTS_21_SIZE_BYTES (48)
#define STAI_TCN_NETWORK_WEIGHTS_21_CHANNEL (2)
#define STAI_TCN_NETWORK_WEIGHTS_21_HEIGHT (3)
#define STAI_TCN_NETWORK_WEIGHTS_21_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_21_BATCH (2)
#define STAI_TCN_NETWORK_WEIGHTS_21_RANK (4)
#define STAI_TCN_NETWORK_WEIGHTS_21_SHAPE \
  { \
    2, 3, 1, 2 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_21_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_21_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_21_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_22_ALIGNMENT (16)
#define STAI_TCN_NETWORK_WEIGHTS_22_NAME "Conv2D_50_bias"
#define STAI_TCN_NETWORK_WEIGHTS_22_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_22_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_WEIGHTS_22_SIZE (2)
#define STAI_TCN_NETWORK_WEIGHTS_22_SIZE_BYTES (8)
#define STAI_TCN_NETWORK_WEIGHTS_22_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_22_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_22_WIDTH (2)
#define STAI_TCN_NETWORK_WEIGHTS_22_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_22_SHAPE \
  { \
    2 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_22_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_22_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_22_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_WEIGHTS_23_ALIGNMENT (32)
#define STAI_TCN_NETWORK_WEIGHTS_23_NAME "Gather_56_param1"
#define STAI_TCN_NETWORK_WEIGHTS_23_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_TCN_NETWORK_WEIGHTS_23_FORMAT (STAI_FORMAT_S32)
#define STAI_TCN_NETWORK_WEIGHTS_23_SIZE (1)
#define STAI_TCN_NETWORK_WEIGHTS_23_SIZE_BYTES (4)
#define STAI_TCN_NETWORK_WEIGHTS_23_CHANNEL (1)
#define STAI_TCN_NETWORK_WEIGHTS_23_HEIGHT (1)
#define STAI_TCN_NETWORK_WEIGHTS_23_WIDTH (1)
#define STAI_TCN_NETWORK_WEIGHTS_23_RANK (1)
#define STAI_TCN_NETWORK_WEIGHTS_23_SHAPE \
  { \
    1 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_23_SCALE_OFFSET_NUM (1)
#define STAI_TCN_NETWORK_WEIGHTS_23_SCALES \
  { \
    1 \
  }
#define STAI_TCN_NETWORK_WEIGHTS_23_OFFSETS \
  { \
    0 \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_TCN_NETWORK_WEIGHTS_NUM (0)
#define STAI_TCN_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_NAMES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_FORMATS \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_SIZES \
  { \
  }
#define STAI_TCN_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_TCN_NETWORK_ACTIVATIONS_NUM (54)
#define STAI_TCN_NETWORK_ACTIVATIONS_ALIGNMENTS \
  { \
    32, 16, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_NAMES \
  { \
    "Reshape_1_out_0", "Reshape_1_out_0_inserted_out92", "Conv2D_5_out_0", "Conv2D_2_out_0", "Reshape_6_out_0", "Reshape_3_out_0", "Relu_7_out_0", "Reshape_8_out_0", "Reshape_8_out_0_inserted_out93", "Conv2D_10_out_0", "Reshape_11_out_0", "Relu_12_out_0", "Add_13_out_0", "Relu_14_out_0", "Reshape_15_out_0", "Reshape_15_out_0_inserted_out94", "Conv2D_17_out_0", "Reshape_18_out_0", "Relu_19_out_0", "Reshape_20_out_0", "Reshape_20_out_0_inserted_out95", "Conv2D_22_out_0", "Reshape_23_out_0", "Relu_24_out_0", "Add_25_out_0", "Relu_26_out_0", "Reshape_27_out_0", "Reshape_27_out_0_inserted_out97", "Conv2D_31_out_0", "Conv2D_28_out_0", "Reshape_32_out_0", "Reshape_29_out_0", "Relu_33_out_0", "Reshape_34_out_0", "Reshape_34_out_0_inserted_out98", "Conv2D_36_out_0", "Reshape_37_out_0", "Relu_38_out_0", "Add_39_out_0", "Relu_40_out_0", "Reshape_41_out_0", "Reshape_41_out_0_inserted_out99", "Conv2D_45_out_0", "Conv2D_42_out_0", "Reshape_46_out_0", "Reshape_43_out_0", "Relu_47_out_0", "Reshape_48_out_0", "Reshape_48_out_0_inserted_out101", "Conv2D_50_out_0", "Reshape_51_out_0", "Relu_52_out_0", "Add_53_out_0", "Relu_54_out_0" \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_FORMATS \
  { \
    STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32, STAI_FORMAT_FLOAT32 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_SIZES \
  { \
    3300, 3300, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 3840, 7680, 7680, 7680, 7680, 7680, 7680, 7680, 7680, 7680, 7680, 7680, 7680, 7680, 7680, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_SIZES_BYTES \
  { \
    13200, 13200, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 15360, 30720, 30720, 30720, 30720, 30720, 30720, 30720, 30720, 30720, 30720, 30720, 30720, 30720, 30720, 480, 480, 480, 480, 480, 480, 480, 480, 480, 480, 480, 480 \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_1_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_NAME "Reshape_1_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_FIRST)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_SIZE (3300)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_SIZE_BYTES (13200)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_CHANNEL (55)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_SHAPE \
  { \
    1, 55, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_1_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_1_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_1_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_2_ALIGNMENT (16)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_NAME "Reshape_1_out_0_inserted_out92"
#define STAI_TCN_NETWORK_ACTIVATIONS_2_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_SIZE (3300)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_SIZE_BYTES (13200)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_CHANNEL (55)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_BATCH (55)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_SHAPE \
  { \
    1, 60, 1, 55 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_2_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_2_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_2_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_3_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_NAME "Conv2D_5_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_BATCH (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_SHAPE \
  { \
    1, 60, 1, 64 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_3_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_3_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_3_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_4_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_NAME "Conv2D_2_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_BATCH (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_SHAPE \
  { \
    1, 60, 1, 64 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_4_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_4_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_4_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_5_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_NAME "Reshape_6_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_5_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_5_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_5_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_6_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_NAME "Reshape_3_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_6_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_6_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_6_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_6_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_7_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_NAME "Relu_7_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_7_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_7_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_7_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_7_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_8_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_NAME "Reshape_8_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_8_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_FIRST)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_SHAPE \
  { \
    1, 64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_8_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_8_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_8_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_9_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_NAME "Reshape_8_out_0_inserted_out93"
#define STAI_TCN_NETWORK_ACTIVATIONS_9_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_BATCH (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_SHAPE \
  { \
    1, 60, 1, 64 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_9_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_9_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_9_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_10_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_NAME "Conv2D_10_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_10_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_BATCH (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_SHAPE \
  { \
    1, 60, 1, 64 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_10_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_10_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_10_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_11_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_NAME "Reshape_11_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_11_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_11_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_11_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_11_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_12_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_NAME "Relu_12_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_12_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_12_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_12_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_12_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_13_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_NAME "Add_13_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_13_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_13_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_13_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_13_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_14_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_NAME "Relu_14_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_14_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_14_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_14_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_14_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_15_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_NAME "Reshape_15_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_15_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_FIRST)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_SHAPE \
  { \
    1, 64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_15_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_15_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_15_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_16_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_NAME "Reshape_15_out_0_inserted_out94"
#define STAI_TCN_NETWORK_ACTIVATIONS_16_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_BATCH (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_SHAPE \
  { \
    1, 60, 1, 64 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_16_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_16_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_16_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_17_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_NAME "Conv2D_17_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_17_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_BATCH (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_SHAPE \
  { \
    1, 60, 1, 64 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_17_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_17_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_17_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_18_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_NAME "Reshape_18_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_18_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_18_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_18_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_18_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_19_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_NAME "Relu_19_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_19_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_19_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_19_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_19_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_20_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_NAME "Reshape_20_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_20_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_FIRST)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_SHAPE \
  { \
    1, 64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_20_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_20_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_20_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_21_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_NAME "Reshape_20_out_0_inserted_out95"
#define STAI_TCN_NETWORK_ACTIVATIONS_21_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_BATCH (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_SHAPE \
  { \
    1, 60, 1, 64 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_21_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_21_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_21_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_22_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_NAME "Conv2D_22_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_22_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_BATCH (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_SHAPE \
  { \
    1, 60, 1, 64 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_22_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_22_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_22_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_23_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_NAME "Reshape_23_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_23_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_23_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_23_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_23_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_24_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_NAME "Relu_24_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_24_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_24_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_24_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_24_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_25_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_NAME "Add_25_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_25_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_25_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_25_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_25_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_26_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_NAME "Relu_26_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_26_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_HEIGHT (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_SHAPE \
  { \
    64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_26_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_26_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_26_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_27_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_NAME "Reshape_27_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_27_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_FIRST)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_SHAPE \
  { \
    1, 64, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_27_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_27_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_27_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_28_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_NAME "Reshape_27_out_0_inserted_out97"
#define STAI_TCN_NETWORK_ACTIVATIONS_28_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_SIZE (3840)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_SIZE_BYTES (15360)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_CHANNEL (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_BATCH (64)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_SHAPE \
  { \
    1, 60, 1, 64 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_28_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_28_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_28_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_29_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_NAME "Conv2D_31_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_29_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_CHANNEL (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_BATCH (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_SHAPE \
  { \
    1, 60, 1, 128 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_29_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_29_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_29_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_30_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_NAME "Conv2D_28_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_30_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_CHANNEL (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_BATCH (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_SHAPE \
  { \
    1, 60, 1, 128 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_30_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_30_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_30_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_31_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_NAME "Reshape_32_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_31_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_HEIGHT (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_SHAPE \
  { \
    128, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_31_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_31_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_31_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_32_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_NAME "Reshape_29_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_32_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_HEIGHT (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_SHAPE \
  { \
    128, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_32_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_32_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_32_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_33_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_NAME "Relu_33_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_33_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_HEIGHT (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_SHAPE \
  { \
    128, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_33_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_33_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_33_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_34_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_NAME "Reshape_34_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_34_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_FIRST)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_CHANNEL (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_SHAPE \
  { \
    1, 128, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_34_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_34_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_34_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_35_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_NAME "Reshape_34_out_0_inserted_out98"
#define STAI_TCN_NETWORK_ACTIVATIONS_35_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_CHANNEL (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_BATCH (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_SHAPE \
  { \
    1, 60, 1, 128 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_35_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_35_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_35_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_36_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_NAME "Conv2D_36_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_36_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_CHANNEL (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_BATCH (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_SHAPE \
  { \
    1, 60, 1, 128 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_36_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_36_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_36_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_37_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_NAME "Reshape_37_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_37_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_HEIGHT (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_SHAPE \
  { \
    128, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_37_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_37_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_37_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_38_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_NAME "Relu_38_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_38_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_HEIGHT (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_SHAPE \
  { \
    128, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_38_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_38_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_38_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_39_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_NAME "Add_39_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_39_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_HEIGHT (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_SHAPE \
  { \
    128, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_39_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_39_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_39_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_40_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_NAME "Relu_40_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_40_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_HEIGHT (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_SHAPE \
  { \
    128, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_40_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_40_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_40_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_41_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_NAME "Reshape_41_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_41_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_FIRST)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_CHANNEL (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_SHAPE \
  { \
    1, 128, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_41_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_41_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_41_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_42_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_NAME "Reshape_41_out_0_inserted_out99"
#define STAI_TCN_NETWORK_ACTIVATIONS_42_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_SIZE (7680)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_SIZE_BYTES (30720)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_CHANNEL (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_BATCH (128)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_SHAPE \
  { \
    1, 60, 1, 128 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_42_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_42_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_42_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_43_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_NAME "Conv2D_45_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_43_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_CHANNEL (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_BATCH (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_SHAPE \
  { \
    1, 60, 1, 2 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_43_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_43_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_43_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_44_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_NAME "Conv2D_42_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_44_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_CHANNEL (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_BATCH (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_SHAPE \
  { \
    1, 60, 1, 2 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_44_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_44_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_44_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_45_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_NAME "Reshape_46_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_45_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_HEIGHT (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_SHAPE \
  { \
    2, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_45_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_45_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_45_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_46_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_NAME "Reshape_43_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_46_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_HEIGHT (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_SHAPE \
  { \
    2, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_46_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_46_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_46_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_47_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_NAME "Relu_47_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_47_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_HEIGHT (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_SHAPE \
  { \
    2, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_47_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_47_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_47_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_48_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_NAME "Reshape_48_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_48_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_FIRST)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_CHANNEL (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_SHAPE \
  { \
    1, 2, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_48_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_48_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_48_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_49_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_NAME "Reshape_48_out_0_inserted_out101"
#define STAI_TCN_NETWORK_ACTIVATIONS_49_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_CHANNEL (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_BATCH (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_SHAPE \
  { \
    1, 60, 1, 2 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_49_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_49_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_49_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_50_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_NAME "Conv2D_50_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_50_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_CHANNEL (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_HEIGHT (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_WIDTH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_BATCH (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_RANK (4)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_SHAPE \
  { \
    1, 60, 1, 2 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_50_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_50_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_50_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_51_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_NAME "Reshape_51_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_51_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_HEIGHT (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_SHAPE \
  { \
    2, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_51_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_51_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_51_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_52_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_NAME "Relu_52_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_52_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_HEIGHT (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_SHAPE \
  { \
    2, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_52_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_52_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_52_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_53_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_NAME "Add_53_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_53_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_HEIGHT (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_SHAPE \
  { \
    2, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_53_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_53_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_53_OFFSETS \
  { \
  }

#define STAI_TCN_NETWORK_ACTIVATIONS_54_ALIGNMENT (32)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_NAME "Relu_54_out_0"
#define STAI_TCN_NETWORK_ACTIVATIONS_54_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE|STAI_FLAG_CHANNEL_LAST)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_SIZE (120)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_SIZE_BYTES (480)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_CHANNEL (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_HEIGHT (2)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_WIDTH (60)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_BATCH (1)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_RANK (3)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_SHAPE \
  { \
    2, 60, 1 \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_54_SCALE_OFFSET_NUM (0)
#define STAI_TCN_NETWORK_ACTIVATIONS_54_SCALES \
  { \
  }
#define STAI_TCN_NETWORK_ACTIVATIONS_54_OFFSETS \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_TCN_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_ACTIVATIONS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_TCN_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_ACTIVATIONS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_TCN_NETWORK_ORIGIN_MODEL_NAME "fall_detection_tcn_OE_3_3_1"
#define STAI_TCN_NETWORK_C_MODEL_NAME "tcn_network"

/*************************** RELATIVE MEMORY POOLS ***************************/
/* no memory pools with relative addresses */

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_TCN_NETWORK_H
